### ISSUE TITLE
Java Requirement:  Which source version

### ISSUE THREAD

**Issue by ghost** [PeterWone/serial-monitor#2]
I'm getting the following error:

```
Java 8 or more recent is required to run. Please download and install a recent Java runtime.
```

I have Java 8 Update 271 currently installed.  I'll deal with this once I get the DOTNET version resolved...

**Comment by ghost** [comment]
This is bogus, it's related to a different extension I have installed...  I'm going to disable it...

**Comment by PeterWone** [comment]
You certainly startled me with that one. It's a dot net core program.

**Comment by ghost** [comment]
Yeah, sorry about that, I never saw that until I started messing with the project and it took a minute to figure out it was a different extension.  It wasn't obvious to me if that was glaring to you...lol
